GET http://localhost:4000/github

###

POST http://localhost:4000/authenticate
Content-Type: application/json

{
    "code": "a6c33e8714b29831c4b8"
}

###

POST http://localhost:4000/messages
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7Im5hbWUiOiJCcnVubyBIaWRla2kgVWVtdXJhIiwiYXZhdGFyX3VybCI6Imh0dHBzOi8vYXZhdGFycy5naXRodWJ1c2VyY29udGVudC5jb20vdS82NDUwOTYyMj92PTQiLCJpZCI6ImRiNWU0ZjZkLTk4MWQtNDBmZC1iZjA1LWYzZTZhNmVkZTk5OSJ9LCJpYXQiOjE2MzQ3MDgzMjcsImV4cCI6MTYzNDc5NDcyNywic3ViIjoiZGI1ZTRmNmQtOTgxZC00MGZkLWJmMDUtZjNlNmE2ZWRlOTk5In0.15SZ7rs5S8y3EL7aVeIkWojQSdRwGay93T_yTVP5lJc

{
    "message": "I am super exited for DoWhile"
}